In [1]:
import numpy as np
# create a multidimensional array from a function of the indices
def indexFunc(i,j,k):
    return k*(i+j)+i
M = np.fromfunction(indexFunc, shape=(3,3,2), dtype=int)
M

array([[[0, 0],
        [0, 1],
        [0, 2]],

       [[1, 2],
        [1, 3],
        [1, 4]],

       [[2, 4],
        [2, 5],
        [2, 6]]])

In [2]:
# array slicing
M[0,:,1:]

array([[0],
       [1],
       [2]])

In [3]:
# create a random 3x3 matrix
A = np.random.rand(3,3)
A

array([[ 0.96480348,  0.57255811,  0.00281168],
       [ 0.23962651,  0.30004438,  0.16600863],
       [ 0.81472991,  0.56607295,  0.91356706]])

In [8]:
# invert
B = np.linalg.inv(A)
B

array([[ 1.43433403, -4.15223832,  0.75010861],
       [-0.66615854,  6.99994906, -1.26994394],
       [-0.86638468, -0.63435853,  1.21254918]])

In [9]:
# matrix multiplication
A.dot(B)

array([[  1.00000000e+00,   1.73038667e-16,  -1.11022302e-16],
       [ -5.55111512e-17,   1.00000000e+00,  -2.77555756e-17],
       [  0.00000000e+00,  -2.22044605e-16,   1.00000000e+00]])

In [6]:
# (A - I\lambda)v = 0
eigenvalues, eigenvectors = np.linalg.eig(A)
(A - np.identity(3)*eigenvalues[0]).dot(eigenvectors[:,0])

array([ -3.60822483e-16,   2.77555756e-17,  -4.16333634e-16])